// front_svelte/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
  
	const apiUrl = 'http://localhost:5000';
  
	let links = [];
	let showCreateForm = false;
	let showDetails = false;
	let currentLink = null;
	let comments = [];
	let filterTag = '';
  
	onMount(async () => {
	  await getLinks();
	});
  
	async function getLinks() {
	  const response = await fetch(`${apiUrl}/links`);
	  links = await response.json();
	}
  
	async function filterLinks() {
	  const response = await fetch(`${apiUrl}/links`);
	  const allLinks = await response.json();
	  links = allLinks.filter(link => link.tags.includes(filterTag));
	}
  
	async function createLink(newLink) {
	  await fetch(`${apiUrl}/links`, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify(newLink),
	  });
	  showCreateForm = false;
	  await getLinks();
	}
  
	async function loadDetails(id) {
	  const response = await fetch(`${apiUrl}/links/${id}`);
	  currentLink = await response.json();
	  comments = await fetch(`${apiUrl}/comments/${id}`).then(res => res.json());
	  showDetails = true;
	}
  
	async function addComment(content) {
	  await fetch(`${apiUrl}/comments`, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ linkId: currentLink._id, content }),
	  });
	  comments = await fetch(`${apiUrl}/comments/${currentLink._id}`).then(res => res.json());
	}
  
	async function voteLink() {
	  await fetch(`${apiUrl}/links/${currentLink._id}/vote`, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ vote: 1 }),
	  });
	  currentLink = await fetch(`${apiUrl}/links/${currentLink._id}`).then(res => res.json());
	}
  </script>
  
  <style>
	body {
	  font-family: 'Arial', sans-serif;
	  background-color: #f9fafb;
	  color: #333;
	  margin: 0;
	  padding: 0;
	}
  
	#logo {
	  color: #4CAF50;
	  text-align: center;
	  margin-bottom: 1.5rem;
	}
  
	.btn {
	  background-color: #4CAF50;
	  color: white;
	  padding: 0.5rem 1rem;
	  border: none;
	  border-radius: 5px;
	  cursor: pointer;
	  transition: background-color 0.3s ease;
	}
  
	.btn:hover {
	  background-color: #45a049;
	}
  
	.input {
	  padding: 0.5rem;
	  border: 1px solid #ddd;
	  border-radius: 5px;
	  width: 200px;
	  margin-right: 1rem;
	}
  
	#filter-create {
	  display: flex;
	  justify-content: space-between;
	  align-items: center;
	  padding: 1rem;
	  background-color: #fff;
	  border-radius: 8px;
	  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	  margin-bottom: 1.5rem;
	}
  
	.space-x-2 {
	  gap: 10px;
	}
  
	#createForm, #details {
	  background-color: #fff;
	  padding: 1.5rem;
	  border-radius: 8px;
	  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	  margin-bottom: 1.5rem;
	}
  
	#createForm input, #createForm button {
	  width: 100%;
	  margin-bottom: 1rem;
	}
  
	#createForm input {
	  padding: 0.75rem;
	  border-radius: 5px;
	  border: 1px solid #ddd;
	}
  
	#createForm button {
	  padding: 0.75rem;
	  background-color: #4CAF50;
	  border: none;
	  color: white;
	  border-radius: 5px;
	  cursor: pointer;
	  transition: background-color 0.3s ease;
	}
  
	#createForm button:hover {
	  background-color: #45a049;
	}
  
	#links {
	  display: grid;
	  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
	  gap: 1.5rem;
	  padding: 1.5rem;
	}
  
	#links .link-card {
	  background-color: #fff;
	  padding: 1.5rem;
	  border-radius: 8px;
	  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	  display: flex;
	  align-items: center;
	  gap: 1rem;
	}
  
	#links img {
	  width: 80px;
	  height: 80px;
	  object-fit: cover;
	  border-radius: 5px;
	}
  
	#comments {
	  margin-top: 1rem;
	}
  
	.comment {
	  background-color: #f1f1f1;
	  padding: 1rem;
	  border-radius: 8px;
	  margin-bottom: 1rem;
	}
  
	textarea {
	  width: 100%;
	  padding: 1rem;
	  border: 1px solid #ddd;
	  border-radius: 5px;
	  resize: none;
	}
  </style>
  
  <main>
	<h1 id="logo" class="text-3xl font-bold">Instacat</h1>
  
	<div id="filter-create">
	  <div class="flex items-center space-x-2">
		<button class="btn" on:click={() => showCreateForm = !showCreateForm}>Crear</button>
		<button class="btn" on:click={() => { showCreateForm = false; showDetails = false; }}>Inicio</button>
	  </div>
	  <div class="flex items-center space-x-2">
		<input type="text" bind:value={filterTag} placeholder="Ingresa un tag" class="input">
		<button class="btn" on:click={filterLinks}>Filtrar</button>
	  </div>
	</div>
  
	{#if showCreateForm}
	  <div id="createForm">
		<form on:submit|preventDefault={(e) => createLink({
		  title: e.target.title.value,
		  description: e.target.description.value,
		  url: e.target.url.value,
		  tags: e.target.tags.value
		})}>
		  <div><label>Título</label><input name="title" type="text" class="input"></div>
		  <div><label>Descripción</label><input name="description" type="text" class="input"></div>
		  <div><label>URL</label><input name="url" type="text" class="input"></div>
		  <div><label>Tags</label><input name="tags" type="text" class="input"></div>
		  <button type="submit" class="btn">Crear</button>
		</form>
	  </div>
	{/if}
  
	{#if showDetails && currentLink}
	  <div id="details">
		<h2>{currentLink.title}</h2>
		<p>{currentLink.description}</p>
		<p>Tags: {currentLink.tags}</p>
		<div class="mt-4">
		  <button class="btn" on:click={voteLink}>Votar</button>
		  <span>Votos: {currentLink.votes}</span>
		</div>
		<h3>Comentarios</h3>
		<div id="comments">
		  {#each comments as comment}
			<div class="comment">{comment.content}</div>
		  {/each}
		</div>
		<form on:submit|preventDefault={(e) => addComment(e.target.commentContent.value)}>
		  <textarea name="commentContent" rows="3" placeholder="Escribe un comentario..."></textarea>
		  <button type="submit" class="btn mt-2">Agregar comentario</button>
		</form>
	  </div>
	{/if}
  
	{#if !showCreateForm && !showDetails}
	  <div id="links">
		{#each links as link}
		  <div class="link-card">
			<img src={link.url} alt="">
			<div>
			  <h3>{link.title}</h3>
			  <p>{link.description}</p>
			  <p class="text-sm text-gray-600">Tags: {link.tags}</p>
			  <button class="text-blue-500" on:click={() => loadDetails(link._id)}>Ver detalles</button>
			</div>
		  </div>
		{/each}
	  </div>
	{/if}
  </main>

// front_vue/src/App.vue
<template>
  <div class="max-w-4xl mx-auto py-6">
    <!-- Logo -->
    <h1 class="text-3xl font-bold text-center mb-6">Instacat</h1>

    <!-- Filtrar y Crear -->
    <div class="flex items-center justify-between bg-white p-4 rounded shadow mb-6">
      <div class="flex items-center space-x-2">
        <button @click="showCreate" class="bg-blue-500 text-white px-4 py-2 rounded">Crear</button>
        <button @click="goHome" class="bg-blue-500 text-white px-4 py-2 rounded">Inicio</button>
      </div>
      <div class="flex items-center space-x-2">
        <input v-model="filterTag" type="text" placeholder="Ingresa un tag" class="border p-2 rounded w-60">
        <button @click="filterLinks" class="bg-green-500 text-white px-4 py-2 rounded">Filtrar</button>
      </div>
    </div>

    <!-- Mostrar Links -->
    <div id="links" class="space-y-4" v-if="!showCreateForm && !showDetailsView">
      <div v-for="link in filteredLinks" :key="link._id" class="bg-white p-4 rounded shadow flex items-center space-x-4">
        <img :src="link.url" alt="" class="w-16 h-16 object-cover">
        <div>
          <h3 class="text-lg font-bold">{{ link.title }}</h3>
          <p>{{ link.description }}</p>
          <p class="text-sm text-gray-600">Tags: {{ link.tags }}</p>
          <button @click="showDetails(link._id)" class="bg-blue-500 text-white px-4 py-2 rounded">Ver detalles</button>
        </div>
      </div>
    </div>

    <!-- Crear Link (Oculto por defecto) -->
    <div v-if="showCreateForm" class="bg-white p-4 rounded shadow mb-6">
      <form @submit.prevent="createLink" class="space-y-4">
        <div>
          <label class="block text-sm font-medium">Título</label>
          <input v-model="newLink.title" type="text" class="border p-2 rounded w-full">
        </div>
        <div>
          <label class="block text-sm font-medium">Descripción</label>
          <input v-model="newLink.description" type="text" class="border p-2 rounded w-full">
        </div>
        <div>
          <label class="block text-sm font-medium">URL</label>
          <input v-model="newLink.url" type="text" class="border p-2 rounded w-full">
        </div>
        <div>
          <label class="block text-sm font-medium">Tags</label>
          <input v-model="newLink.tags" type="text" class="border p-2 rounded w-full">
        </div>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Crear</button>
      </form>
    </div>

    <!-- Detalles (Oculto por defecto) -->
    <div v-if="showDetailsView" class="bg-white p-4 rounded shadow mb-6">
      <h2 class="text-xl font-bold mb-2">{{ linkDetails.title }}</h2>
      <p class="mb-2">{{ linkDetails.description }}</p>
      <p class="text-sm text-gray-600">Tags: {{ linkDetails.tags }}</p>
      <div class="mt-4 flex items-center space-x-4">
        <button @click="voteLink(linkDetails._id)" class="bg-green-500 text-white px-4 py-2 rounded">Votar</button>
        <span>Votos: {{ linkDetails.votes }}</span>
      </div>
      <h3 class="text-lg font-bold mt-4">Comentarios</h3>
      <div v-for="comment in comments" :key="comment._id" class="bg-gray-100 p-2 rounded">{{ comment.content }}</div>
      <form @submit.prevent="addComment">
        <textarea v-model="commentContent" class="w-full p-2 border rounded" rows="3" placeholder="Escribe un comentario..."></textarea>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded mt-2">Agregar comentario</button>
      </form>
      <button @click="goHome" class="bg-blue-500 text-white px-4 py-2 rounded mt-4">Volver</button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      apiUrl: 'http://localhost:5000',
      showCreateForm: false,
      filterTag: '',
      newLink: {
        title: '',
        description: '',
        url: '',
        tags: ''
      },
      links: [],
      filteredLinks: [],
      showDetailsView: false,
      linkDetails: {},
      comments: [],
      commentContent: ''
    };
  },
  methods: {
    async getLinks() {
      const response = await fetch(`${this.apiUrl}/links`);
      this.links = await response.json();
      this.filteredLinks = this.links;
    },
    async filterLinks() {
      const response = await fetch(`${this.apiUrl}/links`);
      const links = await response.json();
      this.filteredLinks = links.filter(link => link.tags.includes(this.filterTag));
    },
    showCreate() {
      this.showCreateForm = true;
      this.showDetailsView = false; // Ocultar detalles al mostrar el formulario de creación
    },
    goHome() {
      this.showCreateForm = false;
      this.showDetailsView = false;
    },
    async createLink() {
      await fetch(`${this.apiUrl}/links`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(this.newLink),
      });
      this.newLink = { title: '', description: '', url: '', tags: '' };
      this.showCreateForm = false;
      this.getLinks();
    },
    async showDetails(id) {
      const response = await fetch(`${this.apiUrl}/links/${id}`);
      this.linkDetails = await response.json();
      this.showDetailsView = true;
      this.showCreateForm = false; // Ocultar el formulario de creación al mostrar los detalles
      this.loadComments(id);
    },
    async loadComments(linkId) {
      const response = await fetch(`${this.apiUrl}/comments/${linkId}`);
      this.comments = await response.json();
    },
    async addComment() {
      if (!this.commentContent.trim()) return;
      await fetch(`${this.apiUrl}/comments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ linkId: this.linkDetails._id, content: this.commentContent }),
      });
      this.commentContent = '';
      this.loadComments(this.linkDetails._id);
    },
    async voteLink(linkId) {
      await fetch(`${this.apiUrl}/links/${linkId}/vote`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ vote: 1 }),
      });
      const updatedLink = await fetch(`${this.apiUrl}/links/${linkId}`).then(res => res.json());
      this.linkDetails.votes = updatedLink.votes;
    }
  },
  mounted() {
    this.getLinks();
  }
};
</script>
